name: teste_mesa_mobile
description: Teste para empresa Mesa Mobile Thinking

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  get: ^3.4.6
  http: ^0.12.2
  toast: ^0.1.5
  flutter_datetime_picker: ^1.4.0
  flutter_pagewise: ^1.2.3
  shared_preferences: ^0.5.6+2
  share: ^0.6.5+2



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

